//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserApplication.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgment.
        /// </summary>
        public static string Acknowledgment {
            get {
                return ResourceManager.GetString("Acknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Note.
        /// </summary>
        public static string AdministrativeNote {
            get {
                return ResourceManager.GetString("AdministrativeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Required.
        /// </summary>
        public static string AreaRequired {
            get {
                return ResourceManager.GetString("AreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Of Receiving.
        /// </summary>
        public static string ChannelOfReceivingID {
            get {
                return ResourceManager.GetString("ChannelOfReceivingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Of Receiving  is Required.
        /// </summary>
        public static string ChannelOfReceivingIDRequired {
            get {
                return ResourceManager.GetString("ChannelOfReceivingIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel is Required.
        /// </summary>
        public static string ChannelRequired {
            get {
                return ResourceManager.GetString("ChannelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Date.
        /// </summary>
        public static string ComplaintDate {
            get {
                return ResourceManager.GetString("ComplaintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliant.
        /// </summary>
        public static string Compliant {
            get {
                return ResourceManager.GetString("Compliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complicated.
        /// </summary>
        public static string Complicated {
            get {
                return ResourceManager.GetString("Complicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is Required.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirate.
        /// </summary>
        public static string EmirateID {
            get {
                return ResourceManager.GetString("EmirateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Note.
        /// </summary>
        public static string ExecutiveNote {
            get {
                return ResourceManager.GetString("ExecutiveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is Required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exisiting.
        /// </summary>
        public static string IsExisiting {
            get {
                return ResourceManager.GetString("IsExisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics Service.
        /// </summary>
        public static string LogisticsService {
            get {
                return ResourceManager.GetString("LogisticsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others Discription.
        /// </summary>
        public static string OthersDiscription {
            get {
                return ResourceManager.GetString("OthersDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is Required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolTransport Service.
        /// </summary>
        public static string SchoolTransportService {
            get {
                return ResourceManager.GetString("SchoolTransportService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Note.
        /// </summary>
        public static string TechnicalNote {
            get {
                return ResourceManager.GetString("TechnicalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Rental Service.
        /// </summary>
        public static string TransportationRentalService {
            get {
                return ResourceManager.GetString("TransportationRentalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
    }
}
